### ISSUE TITLE
flick and dragInsideWithOptions don't work through appium-instruments

### ISSUE THREAD

**Issue by sofaking** [appium/appium-instruments#22]
Not sure if this should be filed here...
Following code does nothing through appium-instruments, although works perfectly with native instruments. 

``` js
var target = UIATarget.localTarget();
var app = target.frontMostApp();
var win = app.mainWindow();
win.collectionViews()[0].flickInsideWithOptions({startOffset:{x:0.3, y:0.5}, endOffset:{x:0.6, y:0.5}});
```

I'm on appium server 1.3.2-beta2, Xcode 6.1, iOS 8.1 and Simulator. Haven't tested on real device though.
I'm executing the script from ruby, but it shouldn't matter.

**Comment by rkavalap** [comment]
Issue moved to [appium/appium #7376](https://github.com/appium/appium/issues/7376) via [**ZenHub**](https://www.zenhub.com/)
