### ISSUE TITLE
ProcessArgument Bug

### ISSUE THREAD

**Issue by Astro03** [appium/appium-instruments#43]
When using the `processArguments` capacity, i've noted that there was a problem with it. 

I use `-e ZOOSK_AUTOMATION_ENABLED 1` to pass an environment variable to instruments. 

https://github.com/appium/appium-instruments/blob/master/lib/instruments.js#L376 adds that capacity to the argument of instruments. 

https://github.com/appium/appium-instruments/blob/master/lib/instruments.js#L427 if you print out the args here, you will note that all the other arguments are split up (i.e. -e, UIASCRIPT, <PATH> are all different elements in the argument array. 

If you take my "string" and split it, then pass ["-e", "ZOOSK_AUTOMATION_ENABLED", "1"]  as distinct elements of an array, the desired behavior of instruments is reached. (I tested this by manually changing it in my fork and running https://github.com/Astro03/appium-instruments/blob/master/lib/instruments.js#L379).

Talking with @bootstraponline, we think that processArguments should probably take an json object.

**Comment by Astro03** [comment]
@imurchie @Jonahss  thoughts?

**Comment by imurchie** [comment]
This seems like a reasonable improvement to me.

**Comment by imurchie** [comment]
What would be the proposed JSON object for `processArguments`?

**Comment by imurchie** [comment]
I think that we ought to have any number of keys in the JSON object, for documentation in a test largely. So if we want to pass in `-f x -r y` we could pass in

```js
var processArguments = {
  "turn-on-x": ["-f", "x"],
  "turn-on-y": ["-r", "y"]
}
```

We will need support, though deprecate, the string version.

```js
if (_.isString(processArguments)) {
  processArguments = {
    args: processArguments.split(' ');
  };
}
```

This will not respect spaces in an argument, though.

**Comment by bootstraponline** [comment]
I think the alternative is to have one key that has an array of all the args. I don't mind either way though.

> `{"args": ["-e", "FOO", "bar"]}`

@Astro03 pointed out `.split(' ')` is going to break on paths with spaces.

**Comment by camillake** [comment]
HI, i fix this issue.
@jlipps

**Comment by Astro03** [comment]
has this been fixed?

**Comment by imurchie** [comment]
Sort of? 

You can pass in a plain string with no `-e` in it, and it will be passed in as-is (at least, this is the behaviour in the current master, and in the upcoming 1.5.2). If you give a string with `-e` in it, the elements will be split on strings such that the following happen:

```
processArguments = "-e flag1 value1 -e flag2 value with spaces -e flag3 value 3"
becomes [..., "-e", "flag1", "value1", "-e", "flag2", "value with spaces", "-e", "flag3", "value 3", ...]
```

Finally, you can send in a hash like `{"flag1": "value1", "flag2": "value2"}` that will be added like above, with `-e`.

I personally think this should be extended to include an environment set and an actual argument set.

See https://github.com/appium/appium-instruments/blob/master/lib/instruments.js#L252-L279

**Comment by GreenJeans** [comment]
@camillake  @imurchie 
I don't think this is working - when passing in a string with -e in it, the whole thing gets surrounded in quotes, causing it to not be recognized.

should be:
    -e flag1 "value1"
is:
    "-e flag1 value1"

**Comment by Astro03** [comment]
@GreenJeans  how are you running this? what are the versions?

**Comment by GreenJeans** [comment]
@Astro03 Appium v. 1.4.13:

        DesiredCapabilities capabilities = new DesiredCapabilities();
        String processArguments = "-e debugController YES";
        capabilities.setCapability("processArguments", processArguments);


Console shows:
    info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPhone 6 (8.1)" /Users/tmorita/Repos/REDACTED "-e debugController YES" -e UIASCRIPT "/Users/tmorita/Library/Application Support/appium/bootstrap/bootstrap-f062718992d59810.js" -e UIARESULTSPATH /tmp/appium-instruments

**Comment by Astro03** [comment]
@GreenJeans  - correct me if i'm wrong @imurchie, but i dont think the "fix" has been pushed to that version.. you need one of the newer versions. 1.5 will definitely have it. 

are you using the appium-dot-app?

**Comment by GreenJeans** [comment]
@Astro03 will check 1.5, thanks.  Yes, using appium-dot-app...no 1.5 available yet, yeah?

**Comment by Astro03** [comment]
@GreenJeans try this.. it's just a beta i been working on - https://bitbucket.org/appium/appium.app/downloads/Appium.app.tmp.1.5.2.tgz 

i have no checked all the functionalities of it yet or if it works fully.

**Comment by GreenJeans** [comment]
@Astro03 IT WORKS!~!!!@#

**Comment by rkavalap** [comment]
Issue moved to [appium/appium #7375](https://github.com/appium/appium/issues/7375) via [**ZenHub**](https://www.zenhub.com/)
