### ISSUE TITLE
Bug when simulators are being killed when Xcode 7 is being used.

### ISSUE THREAD

**Issue by walterdeane** [appium/appium-instruments#47]
The current code will kill all processes that have "Simulator" in the process name. My code was running tests that made calls to a jetty server that contained "Simulator" in the process name and was failing due to appium killing the server. I have a pull request that will make the kill simulators call more robust.

**Comment by rkavalap** [comment]
Issue moved to [appium/appium #7374](https://github.com/appium/appium/issues/7374) via [**ZenHub**](https://www.zenhub.com/)
