### ISSUE TITLE
appium kills all instruments processes

### ISSUE THREAD

**Issue by aluedeke** [appium/appium-instruments#50]
We currently experiencing issues running parallel tests with appium on the same host (which is technical possible since some time).

Fortunately testing fails randomly. We currently believe thats because appium is trying to kill all instrument processes on an host. I think that is a super ugly behaviour and should be changed if possible (or must be at least configurable).

@sebv @lbielski do you have some opinions on that?

**Comment by lbielski** [comment]
Yes, this is not a good behaviour when Appium is not run locally on a single device.
We have successfully tested running multiple Appium sessions in parallel on the same host and it does work (you just have to provide different `tmp` folders as a parameter), but killing all of the `instruments` processes also messes up with other running Appium sessions.

I understand that there is a need to kill `instruments` sometimes and for that we need to link Appium sessions to instruments instance. You can kind of `tag` a process by starting it with an environmental variable, for example `APPIUM_SESSION_ID=<session_id>./`. Then, when you need instruments to be restarted you can search for a process which contains this env variable. On Mac it can be done by `ps -p <pid> -wwwE`. This way you can uniquely identify instruments instance for a specific Appium session.
I would think it makes sense to make this an option for people running Appium sessions on parallel.

Another and simpler option would be to provide an option to disable this behaviour, so when instruments are not working Appium just gives up without trying to fix instruments.

**Comment by aluedeke** [comment]
@jlipps @bootstraponline any feedback?

**Comment by jlipps** [comment]
i do think appium tries to kill all instruments processes, which is bad. i'm not sure if this same strategy is used in appium 1.5 though. @imurchie ?

**Comment by imurchie** [comment]
1.5 does still do this. I'm not sure why, other than it always has.

I'm all for making this the default behaviour and putting the other behind a desired capability. We will have to investigate the best route for this.

**Comment by aluedeke** [comment]
@imurchie we are currently evaluating if providing a custom path to pkill would be sufficient, will ping back when we now more

**Comment by saikrishna321** [comment]
@aluedeke any updates on this ?

**Comment by rkavalap** [comment]
Issue moved to [appium/appium #7373](https://github.com/appium/appium/issues/7373) via [**ZenHub**](https://www.zenhub.com/)
