### ISSUE TITLE
Using through2 instead of through

### ISSUE THREAD

**Issue by moizjv** [appium/appium-instruments#51]
We should upgrade from through to through2, also we should flush out streams for a better performance

@sebv thanks!

**Comment by sebv** [comment]
Not sure if it is going to be a difference, but code need to be cleaned up,should not be any binding there, the wrapping  function should be scoped to the through/through2 object.

**Comment by rkavalap** [comment]
Issue moved to [appium/appium #7372](https://github.com/appium/appium/issues/7372) via [**ZenHub**](https://www.zenhub.com/)
