### ISSUE TITLE
Instruments always logs IWD warning on Xcode 7

### ISSUE THREAD

**Issue by scottdixon** [appium/appium-instruments#56]
appium-instruments always logs an instruments-without-delay warning if it's using Xcode 7:
https://github.com/appium/appium-instruments/blob/master/lib/instruments.js#L251-L256

This can be confusing if the user has [configured IWD to work](https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/iwd_xcode7.md).

Alternative: we could either log an IWD 'success' message or omit this warning.

**Comment by rkavalap** [comment]
Issue moved to [appium/appium #7371](https://github.com/appium/appium/issues/7371) via [**ZenHub**](https://www.zenhub.com/)
