### ISSUE TITLE
Appium always add -e argument into process arguments string

### ISSUE THREAD

**Issue by sergeyhizhnyak** [appium/appium-instruments#67]
According to instruments documentation -e flag is optional.
Previously we were able to pass just command line string to the app file. And now (since 1.5.1) it is always starts with -e.
Which does not work with our app (as it just expects a command line arguments). I believe -e should not be mandatory

**Comment by imurchie** [comment]
This was added at other users' request. I've made a pathway to allow a plain string to be passed in. In the future, the whole `processArgument` structure will be revisited (to allow finer-grained management of the arguments).

**Comment by imurchie** [comment]
Fix is in `appium-instruments@3.7.2`, which will be in Appium 1.5.2, or can be used now if would like.

**Comment by sergeyhizhnyak** [comment]
Thanks - works fine with 3.7.2

**Comment by imurchie** [comment]
Awesome!
