### ISSUE TITLE
xcode-iwd.sh  can create but not UPDATE the paths in the .plist

### ISSUE THREAD

**Issue by chrigrahcisco** [appium/appium-instruments#69]
For reference: https://discuss.appium.io/t/instruments-without-delay-questions-appium-tests-slow/9465/26

If you previously ran xcode-iwd.sh back when appium-instruments lived in a subdirectory of appium and your .plist already includes those directorties then the paths will not get updated due to the following errors:

	CHRIGRAH-M-2038:appium-instruments chrigrah$ sh ./bin/xcode-iwd.sh /Applications/Xcode.app /Users/chrigrah/node_modules/appium-instruments/
	Add: ":EnvironmentVariables" Entry Already Exists
	Add: ":EnvironmentVariables:DYLD_INSERT_LIBRARIES" Entry Already Exists
	Add: ":EnvironmentVariables:LIB_PATH" Entry Already Exists

My workaround was to modify the appium-instruments/bin/xcode-iwd.sh   to use 'Set' instead of 'Add' to force it to update. Changed file is as follows:

	plist_path=$1/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/Developer/Library/LaunchDaemons/com.apple.instruments.deviceservice.plist
	iwd_path=$2/thirdparty/iwd7
	# /usr/libexec/PlistBuddy -c "Add :EnvironmentVariables dict" $plist_path
	/usr/libexec/PlistBuddy -c "Set :EnvironmentVariables:DYLD_INSERT_LIBRARIES string $iwd_path/DTMobileISShim.dylib" $plist_path
	/usr/libexec/PlistBuddy -c "Set :EnvironmentVariables:LIB_PATH string $iwd_path/" $plist_path

**Comment by imurchie** [comment]
Interesting. Thanks for the report. We still, however, want to create the initial entry. Opened a PR to fix.

**Comment by z-vr** [comment]
This will not create new records if they don't exist.

**Comment by chrigrahcisco** [comment]
Just to clarify:

The script needs logic to both scenarios:

1. Create the entries if they do not already exist (what it currently does today)
2. Update them if they do already exist (what happened to me).

I was just providing an example of how I manually edited the script to work in scenario #2. where I had existing entries that were failing to be updated.

**Comment by z-vr** [comment]
@chrigrahcisco it no longer creates new entries since your PR has been merged.
