### ISSUE TITLE
Instrument's blocking after spawning

### ISSUE THREAD

**Issue by nghiadhd** [appium/appium-instruments#78]
Today I run the appium@1.5.3 with appium-instruments@3.8.3

I wrote a test script to test "long running" on multiple real device. The test script just create, do sth in short term and close session repeatedly until reach to timeout (12hours)

However I got blocking issue after spawning the instrument (sometime, not alway) 

```
[debug] [Instruments] Spawning instruments with command: '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /var/folders/my/chbbx01x2x7d9h1nq2qxbqy40000gn/T/tmp-4589Wt7wX8CzRYT1/appium-instruments/instrumentscli0.trace -w 16f2676952bed93b14f52791c9cce7fcd6432fe9 com.bytearc.SafariLauncher -e UIASCRIPT "/Users/xxx/Library/Application Support/appium/bootstrap/bootstrap-866419955ecfbff6.js" -e UIARESULTSPATH /var/folders/my/chbbx01x2x7d9h1nq2qxbqy40000gn/T/tmp-4589Wt7wX8CzRYT1/appium-instruments'
[debug] [Instruments] And launch timeouts (in ms): {"global":90000}

[debug] [Instruments] [INST STDERR] 2016-09-06 15:41:20.185 instruments[6092:81153] WebKit Threading Violation - initial use of WebKit from a secondary thread.
```

Testing devices:

Tablet iPad mini 2G (Cellular) - iOS 9.3.4
iPhone 5s (GSM) - iOS 9.3.4
iPhone 6s - iOS 9.3.4
iPhone 6 - iOS 9.3.2
Tablet iPad Air 2 (Cellular) - iOS 9.0.2

**Comment by jlipps** [comment]
@nghiadhd I'm not seeing any issue here yet? Please paste a link to a gist of the full logs if there is a problem.

**Comment by nghiadhd** [comment]
Hi @jlipps 

Here is my log
https://gist.github.com/nghiadhd/1fb104eb00cb42595b1a59c5508f8834#file-appium-log

Otherwise, I found that "Killing all instruments" is not good solution when running multiple iOS devices in parallel
https://github.com/appium/appium-instruments/blob/master/lib/utils.js#L48-L61

It should be just kill blocking instrument process instead kill all instrument processes (It maybe affect to running instruments of other devices)

My suggestion that we have a timeout & retry 3 times (total times should be smaller than command timeout) when spawning instrument process

**Comment by nghiadhd** [comment]
Hi @jlipps and @imurchie 

Today I continue to investigate this issue and see that 
We spawn instrument successful and waiting for connection which connect to instruments_sock
https://github.com/appium/appium-uiauto/blob/master/lib/uiauto-client.js#L146

But something wrong and no any connection connect to and it blocked at 
`await launchResultPromise`
https://github.com/appium/appium-instruments/blob/master/lib/instruments.js#L180

I would like to check where the code that creates the connection which connects to instruments_sock 

Please help me because it's urgent issue for me
